# Generated by Django 5.2.1 on 2025-05-23 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cpf',
            field=models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='nota_fiscal',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
